# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm config set strict-ssl false
RUN npm config set https-proxy http://mmojdl:heslo@proxy.indra.es:8080
RUN npm config set proxy http://mmojdl:heslo@proxy.indra.es:8080
RUN npm install --verbose